// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	RequestLoginDo
	ResponseLoginDo
	LoginUser
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestLoginDo struct {
	Mobile   string `protobuf:"bytes,1,opt,name=mobile" json:"mobile,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *RequestLoginDo) Reset()                    { *m = RequestLoginDo{} }
func (m *RequestLoginDo) String() string            { return proto1.CompactTextString(m) }
func (*RequestLoginDo) ProtoMessage()               {}
func (*RequestLoginDo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestLoginDo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RequestLoginDo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseLoginDo struct {
	Code  int64      `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg   string     `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Items *LoginUser `protobuf:"bytes,3,opt,name=items" json:"items,omitempty"`
	Count int64      `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
}

func (m *ResponseLoginDo) Reset()                    { *m = ResponseLoginDo{} }
func (m *ResponseLoginDo) String() string            { return proto1.CompactTextString(m) }
func (*ResponseLoginDo) ProtoMessage()               {}
func (*ResponseLoginDo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseLoginDo) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseLoginDo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseLoginDo) GetItems() *LoginUser {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ResponseLoginDo) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type LoginUser struct {
	Uid      int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *LoginUser) Reset()                    { *m = LoginUser{} }
func (m *LoginUser) String() string            { return proto1.CompactTextString(m) }
func (*LoginUser) ProtoMessage()               {}
func (*LoginUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginUser) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto1.RegisterType((*RequestLoginDo)(nil), "proto.RequestLoginDo")
	proto1.RegisterType((*ResponseLoginDo)(nil), "proto.ResponseLoginDo")
	proto1.RegisterType((*LoginUser)(nil), "proto.LoginUser")
}

func init() { proto1.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x09, 0x69, 0x0a, 0x3d, 0x24, 0xa8, 0x4e, 0x50, 0x45, 0x9d, 0xaa, 0x0c, 0xa8, 0x53,
	0x87, 0x32, 0xc1, 0xdc, 0x81, 0x81, 0xc9, 0x88, 0x0f, 0xd0, 0x36, 0xa7, 0x2a, 0x12, 0xf1, 0x05,
	0x9f, 0x0d, 0x5f, 0x1f, 0xf9, 0x5f, 0xa4, 0x4c, 0x79, 0x2f, 0xcf, 0xf7, 0xfc, 0x3b, 0x03, 0x38,
	0x21, 0xb3, 0x1b, 0x0c, 0x5b, 0xc6, 0x2a, 0x7c, 0x9a, 0x03, 0xdc, 0x2b, 0xfa, 0x71, 0x24, 0xf6,
	0x83, 0x2f, 0x9d, 0x3e, 0x30, 0xae, 0x60, 0xde, 0xf3, 0xa9, 0xfb, 0xa6, 0xba, 0xd8, 0x14, 0xdb,
	0x85, 0x4a, 0x0e, 0xd7, 0x70, 0x3b, 0x1c, 0x45, 0xfe, 0xd8, 0xb4, 0xf5, 0x75, 0x48, 0x46, 0xdf,
	0x38, 0x78, 0x50, 0x24, 0x03, 0x6b, 0xa1, 0x5c, 0x83, 0x30, 0x3b, 0x73, 0x1b, 0x4b, 0x4a, 0x15,
	0x34, 0x2e, 0xa1, 0xec, 0xe5, 0x92, 0xa6, 0xbd, 0xc4, 0x67, 0xa8, 0x3a, 0x4b, 0xbd, 0xd4, 0xe5,
	0xa6, 0xd8, 0xde, 0xed, 0x97, 0x11, 0x6e, 0x17, 0x4a, 0xbe, 0x84, 0x8c, 0x8a, 0x31, 0x3e, 0x42,
	0x75, 0x66, 0xa7, 0x6d, 0x3d, 0x0b, 0x75, 0xd1, 0x34, 0xaf, 0xb0, 0x18, 0x4f, 0xfa, 0x72, 0xd7,
	0xb5, 0xe9, 0x3e, 0x2f, 0x3d, 0xb1, 0x5f, 0x58, 0x1f, 0x7b, 0xca, 0xc4, 0xd9, 0xef, 0xdf, 0x01,
	0xfc, 0xd4, 0x27, 0x99, 0x5f, 0x32, 0xf8, 0x06, 0x37, 0x99, 0xfb, 0x29, 0x21, 0x4c, 0x5f, 0x65,
	0xbd, 0x1a, 0x7f, 0x4f, 0xd6, 0x6c, 0xae, 0x4e, 0xf3, 0x10, 0xbc, 0xfc, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x99, 0x8a, 0xd6, 0x0c, 0x5d, 0x01, 0x00, 0x00,
}
